env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  no-param-reassign: [1, { "props": false }]
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
plugins:
  - jest